import Head from 'next/head'
import Navbar from '../components/Navbar'
import HomeHero from '../components/HomeHero'
import HomeBio from '../components/HomeBio'
import SkillSection from '../components/Skillsection'
import AboutBio from '../components/AboutBio'
import Footer from '../components/Footer'


export default function Home() {

  return (
    <div>
      <Head>
        <title>Dennis Badagliacca WebDev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div id='home'>
        <HomeHero />
      </div>
      <HomeBio />

      <div id='skills'>
        <SkillSection />
      </div>

      <div id='about'>
        <AboutBio />
      </div>

      <Footer />

    </div>
  )
}
